<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ysKiyY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ysKiyY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2ysKiyY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2ysKiyY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2ysKiyY\App_KernelDevDebugContainer([
    'container.build_hash' => '2ysKiyY',
    'container.build_id' => 'ef0cee0a',
    'container.build_time' => 1721610663,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ysKiyY');
